<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAddBlog</name>
   <tag></tag>
   <elementGuidId>2666a705-c3f6-444d-9b71-08fd07dca182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[contains(@class,'page-blog')]//div[contains(@class,'action-buttons')]/a[contains(@class,'btn-success')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
