<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBlogTag</name>
   <tag></tag>
   <elementGuidId>8f1788b5-8a2e-4909-aecf-9da71ca1d81d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'content__body')]//div[@id='tab-common']//div[@id='input-tag_addTag']/input[@id='input-tag_tag']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
