<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtBlogBody</name>
   <tag></tag>
   <elementGuidId>5f1586ba-78ac-48f2-937c-55b3c5da1731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[contains(@class,'cke_editable')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
