<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxSelectMember</name>
   <tag></tag>
   <elementGuidId>64e10abf-6463-4c57-8552-657eecf4c5c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='headercontainer-1037']//div[@id='gridcolumn-1052-titleEl']/span[@id='gridcolumn-1052-textEl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
